### ISSUE TITLE
Hearts: Refill your life bar

### ISSUE THREAD

**Issue by m-arnold** [tdelta/SynergyQuest#12]
Currently, players can only lose hearts during battle with monsters. The purpose of this issue is to implement hearts to refill the life bar of the player. They should work as follows:

- If a player collects a heart, then one life of his life bar is restored
- Hearts should drop on monster death (with a modifiable chance)
- After a certain amount of time the hearts are supposed to vanish
- should be animated

**Comment by potamides** [comment]
Fixed with f8f147f.
