### ISSUE TITLE
Color-Traps do not react when moving over them while pulling a box

### ISSUE THREAD

**Issue by ahbnr** [tdelta/SynergyQuest#3]
(discovered by @potamides )

**Steps to reproduce**

1. Open Trap-Maze level (one of the D16 rooms)
2. Pull Sokoban box over a trap. The trap should have an incompatible color (e.g. blue if you are playing red)
3. Observe:
  * The trap does not activate even though it should
  * The trap does not change color

**Notes**

This is caused by the MovementBinder behaviour which deactivates Collider and Rigidbodies. Perhaps this could be solved by replacing the `body.simulated = false` line with `body.isKinematic = true`.
However, since physics-related changes can have many unforeseen effects, this "solution" should be tested and evaluated thoroughly.

**Comment by potamides** [comment]
Fixed with 6bcafe5.
