### ISSUE TITLE
Multiple ghosts spawn on player death (rare)

### ISSUE THREAD

**Issue by ahbnr** [tdelta/SynergyQuest#6]
(reported by @didge-rydu )

**Steps to reproduce**

1. ???
2. Die
3. ???
4. Observe multiple ghosts spawning instead of one.
    This does only happen in rare cases and it is not clear what is causing this issue.
    It has been reported to occur when reloading the controller website while dying / after death.

**Comment by didge-rydu** [comment]
Seems to happen in powers of 2: For example 128 ghosts spawn.

**Comment by didge-rydu** [comment]
**Detailed Steps to Reproduce**
1. Get the player into a dangerous situation
2. Disconnect the controller (close the website)
3. Sustain damage
  - Exception occurs halfway through PlayerController.ChangeHealth, so the health HUD is not displayed and the check for player death is not executed
4. Reconnect the controller
5. Enjoy a ghost for each time PlayerController.ChangeHealth was called
  - I don't know why but Unity seems to execute the rest of the function now
